services:
  mongo:
    image: mongo:8
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - "./services/mongo/data:/data/db"
      - "./services/mongo/init:/docker-entrypoint-initdb.d"
